### ISSUE TITLE
WindowsError [Error 123] (Mac character floating full stop symbol)

### ISSUE THREAD

**Issue by JessicaMoran** [NLNZDigitalPreservation/Safe_mover#4]
File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 373, in <module>
    main(mount_point, destination_folder, log_file_location, on_screen_logging, log_file_name)
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 250, in main
    f = File_Data(item, folder_data, file_tools)
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 32, in **init**
    self.source_modified_date, self.source_created_date, self.source_accessed_date = tools.get_file_dates(self.source_f)
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 92, in get_file_dates
    print "Missing modified date: {}, {}".format(os.path.getmtime(filepath), filepath)
  File "C:\Python27\lib\genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'E:\Kirkcaldie and Stains_Dec 2015\Misc\Bellringers\Bellringer Mockup\1?2 A1 (paths).eps'
[Finished in 48.5s with exit code 1]

**Comment by JessicaMoran** [comment]
got another Windows Error [Error 123]:

Traceback (most recent call last):
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 373, in <module>
    main(mount_point, destination_folder, log_file_location, on_screen_logging, log_file_name)
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 250, in main
    f = File_Data(item, folder_data, file_tools)
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 32, in **init**
    self.source_modified_date, self.source_created_date, self.source_accessed_date = tools.get_file_dates(self.source_f)
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 92, in get_file_dates
    print "Missing modified date: {}, {}".format(os.path.getmtime(filepath), filepath)
  File "C:\Python27\lib\genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'E:\Kirkcaldie and Stains_Dec 2015\Exterior Photos\2007\07 July Store photos Sale?'
[Finished in 425.9s]

**Comment by JessicaMoran** [comment]
and another one

Traceback (most recent call last):
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 373, in <module>
    main(mount_point, destination_folder, log_file_location, on_screen_logging, log_file_name)
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 250, in main
    f = File_Data(item, folder_data, file_tools)
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 32, in **init**
    self.source_modified_date, self.source_created_date, self.source_accessed_date = tools.get_file_dates(self.source_f)
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 92, in get_file_dates
    print "Missing modified date: {}, {}".format(os.path.getmtime(filepath), filepath)
  File "C:\Python27\lib\genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'E:\Kirkcaldie and Stains_Dec 2015\Interior Photos\2015\Interiors - Bookcases?chairs 6-15'
[Finished in 5670.5s]

**Comment by JessicaMoran** [comment]
an another:

Traceback (most recent call last):
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 373, in <module>
    main(mount_point, destination_folder, log_file_location, on_screen_logging, log_file_name)
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 250, in main
    f = File_Data(item, folder_data, file_tools)
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 32, in **init**
    self.source_modified_date, self.source_created_date, self.source_accessed_date = tools.get_file_dates(self.source_f)
  File "\Wlgprdnlfile01\home$\MoranJe\Homedata\Desktop\safe_mover.py", line 92, in get_file_dates
    print "Missing modified date: {}, {}".format(os.path.getmtime(filepath), filepath)
  File "C:\Python27\lib\genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'E:\Kirkcaldie and Stains_Dec 2015\K&S History\History - Adverts\1989-2013\1998? 23-Feb.jpg'
[Finished in 774.2s]

**Comment by jayGattusoNLNZ** [comment]
Issue fixed
